### ISSUE TITLE
Sample project not working for me.

### ISSUE THREAD

**Issue by v2Nitesh** [mtellect/FlutterMulti-ImagePicker#6]
Hi,

I have started learning flutter a week before. Please help me to solve this problem.

I have clone the Github-Repo of https://github.com/mtellect/FlutterMulti-ImagePicker, and tried to run the project but not able to build this it's only giving me the screen which has button named as "Pick-Up-Images", On clicking button it's not working.

I have tried to run the application on Simulator as well as iPhone-6. (Refer attachment )

![multipleimages](https://user-images.githubusercontent.com/7920123/53015668-9bb83400-3471-11e9-8454-1f7948d3e5f1.png)

Here are the error logs :

Syncing files to device iPhone X...
[VERBOSE-2:shell.cc(186)] Dart Error: Unhandled exception:
type 'String' is not a subtype of type 'List<dynamic>'
#0      FlutterMultipleImagePicker.pickMultiImages (package:flutter_multiple_image_picker/flutter_multiple_image_picker.dart:14:16)
<asynchronous suspension>
#1      _MyAppState.initMultiPickUp (package:flutter_multiple_image_picker_example/main.dart:34:53)
<asynchronous suspension>
#2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
#3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
#6      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
#7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
#8      PointerRouter._dispatch (package:flu<…>

**Comment by crimsonsuv** [comment]
The library is only implemented in Android side, In iOS it is returning the iOS version no. in string ... thats why you are getting this error

**Comment by v2Nitesh** [comment]
> The library is only implemented in Android side, In iOS it is returning the iOS version no. in string ... thats why you are getting this error

@crimsonsuv : Thank you for your reply...Do you know any other library which has same behaviour in both Android and iOS...

I have tried [https://github.com/Sh1d0w/multi_image_picker](https://github.com/Sh1d0w/multi_image_picker) but it not providing any customisation...

Thank you in advance.

**Comment by crimsonsuv** [comment]
Hello Nitesh sorry for late reply, I have a library locally set, it works for both ios and android. let me know if you still need it.

**Comment by v2Nitesh** [comment]
Hi @crimsonsuv - Can you please share the step to setup this? Or It's a same process as previous...Have you changed anything in the library ??

Thanks.
Nitesh
